retail_dsy:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: strange-radius-475018-a4
      dataset: retail_dsy
      threads: 4
      timeout_seconds: 300
      location: europe-west1
      keyfile: /secrets/dbt-service-keyfile
